### ISSUE TITLE
qctools >=0.8 need ffmpeg >=3.3 and freetype

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaArea-Utils#125]
I notice that the EIA608 filter in the playback viewer doesn't work in the builds from MediaArea. It should show some text overlay like this: https://www.youtube.com/watch?v=aLfJavQl2Ng.

It looks like freetype isn't used in https://github.com/MediaArea/MediaArea-Utils/blob/49df129318cb7527fda98537326947ae11006162/QCTools/PrepareSource.sh. Could you please add it.

Here's a portion of the installer notes from QCTools that we've used before, though this could probably be updated to freetype2 version 2.7.1 which is at https://sourceforge.net/projects/freetype/files/freetype2/2.7.1/freetype-2.7.1.tar.bz2/download.

```
if [ ! -d freetype ] ; then
	wget https://downloads.sf.net/project/freetype/freetype2/2.5.3/freetype-2.5.3.tar.bz2
	tar jxf freetype-2.5.3.tar.bz2
	mv freetype-2.5.3 freetype
fi
cd freetype
chmod u+x configure
./configure --prefix="`pwd`/usr" --without-harfbuzz
make
make install
cd ..
```

**Comment by JeromeMartinez** [comment]
Fixed (same file names), with script changed and ":" escaping.

BTW, IMHO "EIA608" here is misleading, EIA608 is "Line 21 Data Services" and the only moment EIA608 document references VITC is for saying that captions can be used for caption synchronization in a 3 line paragraph, without technical stuff about it. Maybe it could be changed to "Line21 VITC" or just "VITC" (as VITC may be on other lines e.g. 14/16/18 for NTSC), and keep "EIA608" for line 21 caption decoding.
